### PR TITLE
fixes red background

### PR DESCRIPTION
**Pull request by zags**
I couldn't find Roderick's changes for this so I put together a quick fix.

fixes the red background caused by angular validation of track weights on experiment page
removes bootstrap_customization (moves its remaining lines into styles.css)

### CODE REVIEW

**Comment by elliottyates** [comment]
:+1: @roderickmorales do you have any comments?

**Comment by kyfantaz** [comment]
@roderickmorales probably would say not to change the CSS directly and instead alter the LESS files. Are the LESS files part of the repo yet?

**Comment by rascalking** [comment]
The current state of develop (1778b371204d54dab2f07ed88efddb2739411c2f) doesn't repro the bug.  Don't think we need to merge this.

While trying to track down what was going on, we noticed two things:
* the bug will repro on develop if collectstatic hasn't been run in a local environment
* the bug may repro on develop if local browser cache isn't cleared

**Comment by kyfantaz** [comment]
Then closing this pull request. If the bug still exists, @roderickmorales  is working on it and incorporating it into the LESS pull request.

**Pull request closed without merging**
