### PR TITLE
removes Oracle installation in puppet

### PR DESCRIPTION
**Pull request by elliottyates**

### CODE REVIEW

**Comment by douglashall** [comment]
Does it make sense to add postgres to the puppet script so you don't have to hit an external db when completing dev work?

**Comment by bermudezjd** [comment]
@douglashall: i think we should also consider if using SQLite for local development would work.  The contractors did so for v1 and the transition to Postgres in other hosted environments has been seamless.  I think it's pretty common for Rails and Django apps to be developed in SQLite, plus it's easy to use by default.  I haven't found any significant differences in how you'd work with the Django ORM between the two, but im sure there are some edge cases.  Anyways, just my opinion.

**Comment by douglashall** [comment]
@bermudezjd: Sounds good to me. Keep things vanilla until we find we are in need of something postgres specific.

**Comment by elliottyates** [comment]
2cents: If you're installing via vagrant instead of locally seems like you have everything to gain by using postgres, because you're even closer to the int/qa/prod setup. If you're installing locally, sqlite3 seems more convenient as you don't have to run a postgres server on your host, but vagrant makes that kind of thing easy, doesn't it? (Assuming you can have it running as a daemon from the get-go and never have to administer it.) It does make it harder to just rename the DB and create a new one, I guess. So there is some admin overhead/technical knowledge needed for a long-standing vagrant dev environment. The difference between sqlite and pg is negligible... until it's not. And figuring out what went wrong can be time-consuming. Rails does use sqlite as a default for dev but I think that's for rapid prototyping, not necessarily recommended for long-term dev of a stable app. Just thinking out loud.

**Comment by rascalking** [comment]
I would really recommend not using sqlite unless you have no other choice.  It treats all char/varchart types as text (https://www.sqlite.org/datatype3.html), and has some sql features it flat-out doesn't support (https://www.sqlite.org/omitted.html).  I'd be happy to write any tooling people feel like they'd need to run postgres for local development.

**Comment by cmurtaugh** [comment]
Let's consider the question of whether to use postgres or sqlite separately from this PR.  Removing the Oracle client stuff should happen either way since it's not used by this project.
Adding postgres to the Ansible provisioning script is something that we can work on, but this PR doesn't depend on that.

**Comment by douglashall** [comment]
@cmurtaugh Sounds good. Is there a process for tracking the task of adding postgres to the dev box? Jira?

**Comment by cmurtaugh** [comment]
@douglashall I've added that detail to the task that we have in Trello!

**Comment by elliottyates** [comment]
I think putting technical debt or technical enhancement stuff in Jira is a good start; it can then be prioritized in our backlog grooming sessions, and if it's not clear what the advantages or disavantages are then we can address that in separate discussions.

**Comment by elliottyates** [comment]
(For instance, the dev box could also include a lot of the steps done manually to set up an environment: https://docs.google.com/a/harvard.edu/document/d/1HYNS6JTD5E1t1UwBUxBZxFo2UoK9nlJ4vEaTpxMEYU0/edit?usp=sharing)

**Comment by elliottyates** [comment]
(With the acknowledgement, of course, that some 'technical debt' or technical enhancements are in the devops world, and some are in the scrum team world, and some are both)

**Pull request merged**
