### PR TITLE
CSRF protection for remaining non-angular side-effect-inducing endpoints

### PR DESCRIPTION
**Pull request by elliottyates**
- copy experiment
- delete experiment
- delete IP

### CODE REVIEW

**Comment by douglashall** [comment]
Looks good to me.

**Comment by sapnamysore** [comment]
:+1:

**Comment by roderickmorales** [comment]
Why can't we bind the post via AJAX/JS, so that you don't have that weird looking <form> inside an li?

**Comment by douglashall** [comment]
@roderickmorales Good point. There should probably just be one form and the delete links should send the intervention_point.id as a POST parameter. If we are planning to rework the client-side code here at some point (Angular?), we might just want to call this good enough for now though.

**Comment by elliottyates** [comment]
@roderickmorales and @douglashall yes indeed that would be more elegant. This was a bugfix, essentially, and as much as possible I didn't want to get into changing the controller. I can put some `# todo`s in there to address some of these concerns once we come back to the code, but I don't want to spend any extra time refactoring the app if I can avoid it -- if it still smells too funky, certainly if we as a team feel we can't release such stinky code I can update it.

**Pull request merged**
