### PR TITLE
added id attribute tag for testing -- revised per PR suggestions in (#18...

### PR DESCRIPTION
**Pull request by hktest**

### CODE REVIEW

**Comment by elliottyates** [comment]
:+1:

**Comment by elliottyates** [comment]
It occurs to me there's another issue with that `id` attribute. It looks to me like experiment.name can have spaces and unusual characters in it; thus when it is substituted into the `id`, it will mean problems. `id` is only supposed to have alphanumeric, underscore, and hyphen, I believe -- in any case, spaces definitely will screw it up. So let's think of another way to do this; for instance, we could use a `data-selenium-experiment-name` attribute with the same info, and change the locator to be a CSS locator which points to that `data` attribute, instead of using `id`. Not quite as elegant, but pretty straightforward.

**Comment by rascalking** [comment]
Is there a reason not to just use "id='delete_{{experiment.id}}'"?  We're using that for the url, so I assume it must be unique.

**Comment by elliottyates** [comment]
@rascalking Totally a good idea -- but ab tool was not built to do normal RESTful things -- so AFAIK you can't e.g. get the ID back automatically when you create a new item. In the testing suite, you only know the name you're trying to create, so you'd have to find another element in the same chunk of the page that had the name as e.g. text (the title of the experiment, I guess) then get an attribute from that element that had the experiment.id in it, then select the delete link with that id. So it would be a multi-step process. Can you think of another one-step way? I agree that `data-*` attributes are not as nice as using `id`.

**Comment by rascalking** [comment]
Talked to @elliottyates offline about this...I was missing the fact that the id isn't going to be user-visible (and thus selenium-visible) without some more munching around in the page.  Agreed that it makes the most sense to use a data attribute.

**Comment by hktest** [comment]
modified.  @elliottyates, could you take one more look at the change to see if there's anything else before I merge - thanks!

**Comment by roderickmorales** [comment]
@hktest can we talk about this before you merge? just to make sure I'm understating what you want to do

**Comment by elliottyates** [comment]
I hate to say it, but currently experiment.name allows double-quotes as valid input, along with, for example, html code. It's a little unclear to me whether we're safe -- in Chrome although Django doesn't escape the HTML as I'd expect it still doesn't break anything on our pages. For instance, naming an experiment:
`Are">quotes""allowed?</a></div>how about<a href="youtube.com">clickme!</a>tags?and</h3>breakouts?`
...doesn't actually break out of the experiment title `h3` tag or the `a` tag in the delete. I'm not sure why, although I'm sure there's a simple explanation. In any case I'm not sure it's safe to allow those kinds of characters in the model... let's talk tomorrow about it.

**Comment by elliottyates** [comment]
Looked at it again this morning with Dave, Hiu-Kei, and Marlee. The escaping is actually happening as expected -- it's just not showing the html entity substitution in the Chrome debugger DOM view (only in the actual page source). So this is :+1: good to go after testing.

**Comment by hktest** [comment]
Tested locally and working as desired.  Super AWESOME!  Thanks @elliottyates for the feedback!  Merging to develop.

**Pull request merged**
