### PR TITLE
Feature/new ui

### PR DESCRIPTION
**Pull request by roderickmorales**
Contains the design implementation for the AB tool v1. It covers the dashboard, add/edit experiment and add/edit intervention points

### CODE REVIEW

**Comment by roderickmorales** [comment]
This PR might seem long but I didn't know how to leave out the libraries that are been used. If you ignore the libraries used (e.g. bootstrap, fontawesome) then it shouldn't be too bad.

**Comment by zags** [comment]
it appears font-awesome.min.css is being used; deleting font-awesome.css

**Comment by zags** [comment]
can we delete  ab_tool/static/ab_tool/css/font-awesome-4.2.0/less/ and  ab_tool/static/ab_tool/css/font-awesome-4.2.0/scss/?

**Comment by zags** [comment]
I pushed some changes.  I'd love to delete some of the other files.

:+1: 

I'm going to merge it so the other pull requests can move forward

**Pull request merged**
