### PR TITLE
Sprint 18 TLT-1066 Organize requirements

### PR DESCRIPTION
**Pull request by douglashall**
@elliottyates 
@eparker71 

Moved dev-only requirements to local.txt
Moved TLT package requirements out of base.txt
Verified that package versions are appropriate for the given environment.

### CODE REVIEW

**Comment by elliottyates** [comment]
I agree that the mock & jasmine libraries shouldn't be in base.txt. How about the others, though -- they are currently essential to the program in any environment, aren't they? They aren't swappable at the moment without changing the source code in multiple places (that is, they aren't libraries with a single set up module that can be easily replaced by someone who wishes to use a separate e.g. LTI authorization library). The Canvas SDK itself is OS, but that does present a problem for the closed-source django_auth_lti module; to release this project as OS but have it use a non-OS library (which explicitly states it is to be used for 'internal purposes' only) seems like an oversight, and presents an architectural choice we'll have to make at some point. Both libraries are used throughout the code though, so why would we move them into individual requirements files? (Perhaps there's a good reason, I'm just not aware of it.) Thanks.

**Comment by bermudezjd** [comment]
From the DevOps side, we'd like to get away from environment-specific requirements files and handle those differences with environment variables in settings.  This project looks a little different from our other projects because it was easier to move things out of the various settings and requirements files and get to the .  @elliottyates and I had started to discuss the need to separate out testing requirements now that the list had grown (I wasn't opposed to just having mock included everywhere when that was the only testing package, despite that being an anti-pattern).  There are a few ways that could be done, but the easiest for now would probably be to have the test packages moved into local.txt.

As for the auth_lti library, the intent all along was for that to be turned into an open source library like the canvas_sdk.  There's nothing Harvard specific about it, but there are currently Canvas dependencies.  I think there were some JIRA issues to investigate moving that project to penzance as an open source reusable Django app?

**Comment by elliottyates** [comment]
@bermudezjd I know there were JIRA issues for moving the django oauth lib out of the project and making is a reusable library, not sure about the auth_lti library. Makes sense though!

**Comment by douglashall** [comment]
The short term goal here is to allow us to customize the version of the TLT maintained packages by environment. This will help me with a local dev setup I'm working on that will allow me to point to local repos for those TLT maintained packages. This shouldn't move us away in anyway from the longer term plan it sounds like you guys are working on for environment specific requirements (which I would love to hear more about).

**Comment by elliottyates** [comment]
Perhaps @bermudezjd can look at the other local dev vagrant project you're working on (https://github.com/Harvard-University-iCommons/tlt-vagrant) and see if it will fit into the environment-variable framework he has planned? If so we can move to that and you can adjust your local dev project accordingly. It doesn't feel great proliferating duplicate requirements across multiple files if we can avoid that. If the benefits of the project you're working on outweigh the relative inconvenience (as you say, hopefully short-term) of the requirements files getting harder to maintain, it's not a big deal, but we should make comments in the files to that effect. This will probably be easier to discuss in person, though, as I'm not sure what the local dev project is or why we need it exactly. I look forward to learning more.

**Comment by bermudezjd** [comment]
@douglashall: we ran into the problem of developers wanting to have editable versions of libraries we maintain before and one solution we came up with was to ignore requirements files other than those explicitly listed for environments.  If you take a look at the .gitignore in icommons_ext_tools you can see how that works.  It would allow you to create your own requirements file that points to different versions of libraries.  That said, we do want to have the same version of dependent libraries in each environment.  The idea would be to make any updates you want to the dependent library in the above workflow, cut a new version, update the base requirements with that new version, and allow that to move through the various environments.  I also don't think we view this as a long term goal, but we can discuss offline if you like.

**Comment by douglashall** [comment]
One issue I had with the vagrant setup was having the pip install process run during provisioning and for some reason not being able to access the private git repos. Let me verify that this is still a problem, if not, we won't need these changes.

I'd still love to get an outline of how you we will handle requirements in the future and when it will be implemented.

**Comment by douglashall** [comment]
Working around ssh issue with installing pip requirements from private repos for now by installing them after vagrant provisioning.

**Pull request closed without merging**
